# Generated by Django 4.0.6 on 2022-07-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]
    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name_plural': 'ToDo app'},
        ),
        migrations.AlterModelTable(
            name='todo',
            table='TODO',
        ),
    ]
