# Generated by Django 4.0.6 on 2022-07-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='about_t',
        ),
    ]
